# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flowers', '0002_auto_20180119_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='route',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(default='no-img.jpg', upload_to='static/'),
        ),
    ]
